import WelcomeText from "./publicView/Components/WelcomeText";
import About from "./publicView/About";

export const pagesRouts = [
	{
		name: "home",
		component: WelcomeText,
		path: "/",
	},
	{
		name: "about",
		component: About,
		path: "about",
	},
];

export const LeftSidebarRoutes = [
	{
		id: 1,
		name: "Quality Standards",
		path: "61-quality-standards",
		hasSubItem: true,
		parent_id: null,
	},
	{
		id: 2,
		name: "Air Pollution",
		path: "71-air-polution",
		hasSubItem: false,
		parent_id: 1,
	},
	{
		id: 3,
		name: "Water Pollution",
		path: "72-water-polution",
		hasSubItem: false,
		parent_id: 1,
	},
	{
		id: 4,
		name: "Noise Pollution",
		path: "73-noise--polution",
		hasSubItem: false,
		parent_id: 1,
	},
	{
		id: 5,
		name: "Vehicular Pollution",
		path: "74-vehicular-polution",
		hasSubItem: false,
		parent_id: 1,
	},
	{
		id: 6,
		name: "Industry",
		path: "75-industry",
		hasSubItem: false,
		parent_id: 1,
	},
	{
		id: 7,
		name: "CETP-Inlet standards",
		path: "151-cetp-inlet-standards-",
		hasSubItem: false,
		parent_id: 1,
	},
	{
		id: 8,
		name: "Brick Klins",
		path: "219-brick-klins",
		hasSubItem: false,
		parent_id: 1,
	},
	{
		id: 9,
		name: "Consent Management",
		path: "62-consent-management",
		hasSubItem: true,
		parent_id: null,
	},
	{
		id: 10,
		name: "Fee Consent",
		path: "78-fee-consent",
		hasSubItem: false,
		parent_id: 9,
	},
	{
		id: 11,
		name: "Related Orders",
		path: "82-related-orders",
		hasSubItem: false,
		parent_id: 9,
	},
	{
		id: 12,
		name: "Data Bank",
		path: "64-data-bank",
		hasSubItem: true,
		parent_id: null,
	},
	{
		id: 13,
		name: "Air Quality Data",
		path: "95-air-quality-data",
		hasSubItem: false,
		parent_id: 12,
	},
	{
		id: 14,
		name: "Water Quality Data",
		path: "96-water-quality-data",
		hasSubItem: true,
		parent_id: 12,
	},
	{
		id: 15,
		name: "Water Quality of River Ganga Pre-Post (Major Snans)",
		path: "206-water-quality-of-river-ganga-pre-post-(major-snans)",
		hasSubItem: false,
		parent_id: 14,
	},
	{
		id: 16,
		name: "Noise Data",
		path: "97-noise-data",
		hasSubItem: false,
		parent_id: 12,
	},
	{
		id: 17,
		name: "AQI-Weekly Data",
		path: "98-aqi-weekly-data",
		hasSubItem: false,
		parent_id: 12,
	},
	{
		id: 18,
		name: "Ground Water",
		path: "100-ground-water",
		hasSubItem: false,
		parent_id: 12,
	},
	{
		id: 19,
		name: "Sewage Treatment Plant (STP)",
		path: "184-sewage-treatment-plant-(stp)",
		hasSubItem: false,
		parent_id: 12,
	},
	{
		id: 20,
		name: "Employee",
		path: "70-employee",
		hasSubItem: true,
		parent_id: null,
	},
	{
		id: 21,
		name: "Head Office",
		path: "87-head-office",
		hasSubItem: false,
		parent_id: 20,
	},
	{
		id: 22,
		name: "Regional Offices",
		path: "143-regional-offices",
		hasSubItem: true,
		parent_id: 20,
	},
	{
		id: 23,
		name: "Regional Office,Dehradun",
		path: "88-regional-office,dehradun",
		hasSubItem: false,
		parent_id: 22,
	},
	{
		id: 24,
		name: "Regional Office, Kashipur",
		path: "139-regional-office,-kashipur",
		hasSubItem: false,
		parent_id: 22,
	},
	{
		id: 25,
		name: "Regional Office, Roorkee",
		path: "138-regional-office,-roorkee",
		hasSubItem: false,
		parent_id: 22,
	},
	{
		id: 26,
		name: "Regional Office,Haldwani",
		path: "89-regional-office,haldwani",
		hasSubItem: false,
		parent_id: 22,
	},
	{
		id: 27,
		name: "Direction under Air/Water/EP Act",
		path: "35-direction-under-air-water-ep-act",
		hasSubItem: false,
		parent_id: null,
	},
	{
		id: 28,
		name: "Photo Gallery",
		path: "/photogallery",
		hasSubItem: false,
		parent_id: null,
	},
	{
		id: 29,
		name: "Related Links",
		path: "/weblinks",
		hasSubItem: false,
		parent_id: null,
	},
	{
		id: 30,
		name: "Guidelines",
		path: "/contents/listing/7/145-guidelines",
		hasSubItem: false,
		parent_id: null,
	},
	{
		id: 31,
		name: "List of Authorized Recyclers",
		path: "147-list-of-authorized-recyclers",
		hasSubItem: true,
		parent_id: null,
	},
	{
		id: 32,
		name: "E-Waste",
		path: "187-e-waste",
		hasSubItem: false,
		parent_id: 31,
	},
	{
		id: 33,
		name: "Hazardous Waste",
		path: "216-hazardous-waste",
		hasSubItem: false,
		parent_id: 31,
	},
	{
		id: 34,
		name: "Plastic Waste",
		path: "222-plastic-waste",
		hasSubItem: false,
		parent_id: 31,
	},
	{
		id: 35,
		name: "SOP for Recycling/Reprocessing & Reuse of the Materials",
		path: "10/152-sop-for-recycling-reprocessing-reuse-of-the-materials",
		hasSubItem: true,
		parent_id: null,
	},
	{
		id: 36,
		name: "Hazardous Waste_SOP under Rule 9",
		path: "223-hazardous-waste_sop-under-rule-9",
		hasSubItem: false,
		parent_id: 35,
	},
	{
		id: 37,
		name: "River Rejuvenation Committee, Uttarakhand.",
		path: "166-river-rejuvenation-committee,-uttarakhand.",
		hasSubItem: true,
		parent_id: null,
	},
	{
		id: 38,
		name: "Action Plan for Rejuvenation of Polluted River Stretch",
		path: "167-action-plan-for-rejuvenation-of-polluted-river-stretch",
		hasSubItem: false,
		parent_id: 37,
	},
	{
		id: 39,
		name: "Water Quality of Polluted River Stretch",
		path: "168-water-quality-of-polluted-river-stretch",
		hasSubItem: false,
		parent_id: 37,
	},
	{
		id: 40,
		name: "Order of Hon'ble NGT",
		path: "169-order-of-honble-ngt",
		hasSubItem: false,
		parent_id: 37,
	},
	{
		id: 41,
		name: "Letter/Notices etc",
		path: "170-letter-notices-etc",
		hasSubItem: false,
		parent_id: 37,
	},
	{
		id: 42,
		name: "RRC, Uttarakhand-Minutes of Meeting",
		path: "182-rrc,-uttarakhand-minutes-of-meeting",
		hasSubItem: false,
		parent_id: 37,
	},
	{
		id: 43,
		name: "Directions",
		path: "203-directions",
		hasSubItem: false,
		parent_id: 37,
	},
	{
		id: 44,
		name: "Reports by SPCBs",
		path: "171-reports-by-spcbs",
		hasSubItem: true,
		parent_id: null,
	},
	{
		id: 45,
		name: "Annual Reports by State Pollution Control Board",
		path: "172-annual-reports-by-state-pollution-control-board",
		hasSubItem: false,
		parent_id: 44,
	},
	{
		id: 46,
		name: "Annual Reports under Various Rules",
		path: "174-annual-reports-under-various-rules",
		hasSubItem: true,
		parent_id: 44,
	},
	{
		id: 47,
		name: "BMW Reports",
		path: "176-bmw-reports",
		hasSubItem: false,
		parent_id: 46,
	},
	{
		id: 48,
		name: "MSW Reports",
		path: "177-msw-reports",
		hasSubItem: false,
		parent_id: 46,
	},
	{
		id: 49,
		name: "E-waste",
		path: "178-e-waste",
		hasSubItem: false,
		parent_id: 46,
	},
	{
		id: 50,
		name: "Plastic Waste",
		path: "179-plastic-waste",
		hasSubItem: false,
		parent_id: 46,
	},
	{
		id: 51,
		name: "Hazardous Waste",
		path: "180-hazardous-waste-",
		hasSubItem: false,
		parent_id: 46,
	},
	{
		id: 52,
		name: "Construction & Demolition Waste",
		path: "209-construction-demolition-waste-",
		hasSubItem: false,
		parent_id: 46,
	},
	{
		id: 53,
		name: "Battery Waste",
		path: "211-battery-waste",
		hasSubItem: false,
		parent_id: 46,
	},
	{
		id: 54,
		name: "Technical Reports",
		path: "175-technical-reports",
		hasSubItem: false,
		parent_id: 44,
	},
	{
		id: 55,
		name: "SoE Report",
		path: "181-soe-report",
		hasSubItem: false,
		parent_id: 44,
	},
	{
		id: 56,
		name: "Air Action Plan",
		path: "183-air-action-plan",
		hasSubItem: false,
		parent_id: null,
	},
	{
		id: 57,
		name: "DISPLAY BOARD FOR HAZARDOUS WASTE/ENVIRONMENTAL DATA",
		path: "185-display-board-for-hazardous-waste-environmental-data",
		hasSubItem: false,
		parent_id: null,
	},
	{
		id: 58,
		name: "Reports by CPCB",
		path: "204-reports-by-cpcb",
		hasSubItem: false,
		parent_id: null,
	},
	{
		id: 59,
		name: "Inspection Reports in Compliance to Court Orders",
		path: "212-inspection-reports-in-compliance-to-court-orders",
		hasSubItem: true,
		parent_id: null,
	},
	{
		id: 60,
		name: "Inspection Reports",
		path: "214-inspection-reports",
		hasSubItem: true,
		parent_id: 59,
	},
	{
		id: 61,
		name: "Directions Issued",
		path: "215-directions-issued",
		hasSubItem: false,
		parent_id: 60,
	},
	{
		id: 62,
		name: "Draft-District Environment Plan/State Environment Plan",
		path: "218-draft-district-environment-plan-state-environment-plan",
		hasSubItem: false,
		parent_id: null,
	},
	{
		id: 63,
		name: "Mission LiFE",
		path: "227-mission-life",
		hasSubItem: false,
		parent_id: null,
	},
];
